export const INDUSTRIES = [
  "Technology",
  "Health Tech",
  "Fintech",
  "EdTech",
  "Climate & Sustainability",
  "Creative & Design",
  "Consulting",
  "Legal",
  "Finance & Banking",
  "Real Estate",
  "Media & Entertainment",
  "Retail & E-commerce",
  "Manufacturing",
  "Non-profit & Social Impact",
  "AI & Machine Learning",
  "Blockchain & Web3",
  "SaaS",
  "Gaming",
  "Food & Beverage",
  "Travel & Hospitality",
  "Logistics & Supply Chain",
  "Agriculture",
  "Automotive",
  "Telecommunications",
  "Energy",
  "Aerospace & Defence",
  "Cybersecurity",
  "Biotech & Pharma",
  "HR & Recruitment",
  "Marketing & Advertising",
];

export const COUNTRIES = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Singapore",
  "United Arab Emirates",
  "Netherlands",
  "Japan",
  "South Korea",
  "Israel",
  "Sweden",
  "Switzerland",
  "Brazil",
  "Mexico",
  "Nigeria",
  "Kenya",
  "South Africa",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Thailand",
  "Malaysia",
  "China",
  "Hong Kong",
  "New Zealand",
  "Ireland",
  "Spain",
  "Italy",
  "Poland",
  "Turkey",
  "Saudi Arabia",
  "Egypt",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "Denmark",
  "Norway",
  "Finland",
  "Belgium",
  "Austria",
  "Portugal",
  "Czech Republic",
  "Romania",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
];

export const SKILLS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "React",
  "Node.js",
  "Machine Learning",
  "Data Science",
  "Product Management",
  "UI/UX Design",
  "Backend Development",
  "Frontend Development",
  "Mobile Development",
  "DevOps",
  "Cloud Architecture",
  "Blockchain",
  "Smart Contracts",
  "Growth Marketing",
  "SEO",
  "Content Strategy",
  "Sales",
  "Business Development",
  "Finance & Accounting",
  "Legal & Compliance",
  "Operations",
  "HR & People",
  "Supply Chain",
  "Project Management",
  "Agile / Scrum",
  "Data Engineering",
  "Cybersecurity",
  "Graphic Design",
  "Video Production",
  "Copywriting",
  "Public Speaking",
  "Fundraising",
  "Venture Capital",
  "Angel Investing",
  "Community Building",
  "Research",
  "Hardware Engineering",
  "Embedded Systems",
  "Robotics",
  "NLP",
  "Computer Vision",
  "iOS Development",
  "Android Development",
  "Flutter",
  "React Native",
  "AWS",
  "GCP",
  "Azure",
  "Docker",
  "Kubernetes",
  "PostgreSQL",
  "MongoDB",
  "GraphQL",
  "REST APIs",
  "System Design",
  "Leadership",
  "Strategy",
];

export const INDUSTRY_SKILL_ROLE_MAP: Record<string, string[]> = {
  "Fintech": ["Finance & Accounting", "Sales", "Business Development", "Product Management", "Data Science", "Legal & Compliance", "Operations", "Strategy"],
  "Technology": ["Frontend Development", "Backend Development", "React", "Node.js", "System Design", "DevOps", "Product Management", "Leadership"],
  "Health Tech": ["Product Management", "Data Science", "Machine Learning", "Operations", "Legal & Compliance", "Research"],
  "AI & Machine Learning": ["Machine Learning", "Data Science", "NLP", "Computer Vision", "Python", "Data Engineering", "Research"],
  "SaaS": ["Product Management", "Frontend Development", "Backend Development", "Sales", "Growth Marketing", "Operations"],
  "Cybersecurity": ["Cybersecurity", "Backend Development", "Cloud Architecture", "DevOps", "Legal & Compliance", "System Design"],
  "Retail & E-commerce": ["Sales", "Growth Marketing", "SEO", "Content Strategy", "Operations", "Supply Chain", "Product Management"],
  "Marketing & Advertising": ["Growth Marketing", "SEO", "Content Strategy", "Copywriting", "Sales", "Business Development"],
  "Creative & Design": ["UI/UX Design", "Graphic Design", "Video Production", "Copywriting", "Product Management"],
};
